# coding: utf-8

"""
    LAMP Platform

    The LAMP Platform API.  # noqa: E501

    OpenAPI spec version: 0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from openapi_client.api_client import ApiClient


class TypeApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def type_delete_attachment(self, type_id, attachment_key, **kwargs):  # noqa: E501
        """type_delete_attachment  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.type_delete_attachment(type_id, attachment_key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str type_id: (required)
        :param str attachment_key: (required)
        :return: Response
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.type_delete_attachment_with_http_info(type_id, attachment_key, **kwargs)  # noqa: E501
        else:
            (data) = self.type_delete_attachment_with_http_info(type_id, attachment_key, **kwargs)  # noqa: E501
            return data

    def type_delete_attachment_with_http_info(self, type_id, attachment_key, **kwargs):  # noqa: E501
        """type_delete_attachment  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.type_delete_attachment_with_http_info(type_id, attachment_key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str type_id: (required)
        :param str attachment_key: (required)
        :return: Response
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['type_id', 'attachment_key']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method type_delete_attachment" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'type_id' is set
        if ('type_id' not in local_var_params or
                local_var_params['type_id'] is None):
            raise ValueError("Missing the required parameter `type_id` when calling `type_delete_attachment`")  # noqa: E501
        # verify the required parameter 'attachment_key' is set
        if ('attachment_key' not in local_var_params or
                local_var_params['attachment_key'] is None):
            raise ValueError("Missing the required parameter `attachment_key` when calling `type_delete_attachment`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'type_id' in local_var_params:
            path_params['type_id'] = local_var_params['type_id']  # noqa: E501
        if 'attachment_key' in local_var_params:
            path_params['attachment_key'] = local_var_params['attachment_key']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Authorization']  # noqa: E501

        return self.api_client.call_api(
            '/type/{type_id}/attachment/{attachment_key}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Response',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def type_delete_dynamic_attachment(self, type_id, attachment_key, **kwargs):  # noqa: E501
        """type_delete_dynamic_attachment  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.type_delete_dynamic_attachment(type_id, attachment_key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str type_id: (required)
        :param str attachment_key: (required)
        :return: Response
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.type_delete_dynamic_attachment_with_http_info(type_id, attachment_key, **kwargs)  # noqa: E501
        else:
            (data) = self.type_delete_dynamic_attachment_with_http_info(type_id, attachment_key, **kwargs)  # noqa: E501
            return data

    def type_delete_dynamic_attachment_with_http_info(self, type_id, attachment_key, **kwargs):  # noqa: E501
        """type_delete_dynamic_attachment  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.type_delete_dynamic_attachment_with_http_info(type_id, attachment_key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str type_id: (required)
        :param str attachment_key: (required)
        :return: Response
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['type_id', 'attachment_key']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method type_delete_dynamic_attachment" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'type_id' is set
        if ('type_id' not in local_var_params or
                local_var_params['type_id'] is None):
            raise ValueError("Missing the required parameter `type_id` when calling `type_delete_dynamic_attachment`")  # noqa: E501
        # verify the required parameter 'attachment_key' is set
        if ('attachment_key' not in local_var_params or
                local_var_params['attachment_key'] is None):
            raise ValueError("Missing the required parameter `attachment_key` when calling `type_delete_dynamic_attachment`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'type_id' in local_var_params:
            path_params['type_id'] = local_var_params['type_id']  # noqa: E501
        if 'attachment_key' in local_var_params:
            path_params['attachment_key'] = local_var_params['attachment_key']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Authorization']  # noqa: E501

        return self.api_client.call_api(
            '/type/{type_id}/dynamic_attachment/{attachment_key}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Response',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def type_get_attachment(self, type_id, attachment_key, **kwargs):  # noqa: E501
        """type_get_attachment  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.type_get_attachment(type_id, attachment_key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str type_id: (required)
        :param str attachment_key: (required)
        :return: Response
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.type_get_attachment_with_http_info(type_id, attachment_key, **kwargs)  # noqa: E501
        else:
            (data) = self.type_get_attachment_with_http_info(type_id, attachment_key, **kwargs)  # noqa: E501
            return data

    def type_get_attachment_with_http_info(self, type_id, attachment_key, **kwargs):  # noqa: E501
        """type_get_attachment  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.type_get_attachment_with_http_info(type_id, attachment_key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str type_id: (required)
        :param str attachment_key: (required)
        :return: Response
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['type_id', 'attachment_key']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method type_get_attachment" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'type_id' is set
        if ('type_id' not in local_var_params or
                local_var_params['type_id'] is None):
            raise ValueError("Missing the required parameter `type_id` when calling `type_get_attachment`")  # noqa: E501
        # verify the required parameter 'attachment_key' is set
        if ('attachment_key' not in local_var_params or
                local_var_params['attachment_key'] is None):
            raise ValueError("Missing the required parameter `attachment_key` when calling `type_get_attachment`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'type_id' in local_var_params:
            path_params['type_id'] = local_var_params['type_id']  # noqa: E501
        if 'attachment_key' in local_var_params:
            path_params['attachment_key'] = local_var_params['attachment_key']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Authorization']  # noqa: E501

        return self.api_client.call_api(
            '/type/{type_id}/attachment/{attachment_key}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Response',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def type_get_dynamic_attachment(self, type_id, attachment_key, **kwargs):  # noqa: E501
        """type_get_dynamic_attachment  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.type_get_dynamic_attachment(type_id, attachment_key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str type_id: (required)
        :param str attachment_key: (required)
        :return: Response
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.type_get_dynamic_attachment_with_http_info(type_id, attachment_key, **kwargs)  # noqa: E501
        else:
            (data) = self.type_get_dynamic_attachment_with_http_info(type_id, attachment_key, **kwargs)  # noqa: E501
            return data

    def type_get_dynamic_attachment_with_http_info(self, type_id, attachment_key, **kwargs):  # noqa: E501
        """type_get_dynamic_attachment  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.type_get_dynamic_attachment_with_http_info(type_id, attachment_key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str type_id: (required)
        :param str attachment_key: (required)
        :return: Response
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['type_id', 'attachment_key']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method type_get_dynamic_attachment" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'type_id' is set
        if ('type_id' not in local_var_params or
                local_var_params['type_id'] is None):
            raise ValueError("Missing the required parameter `type_id` when calling `type_get_dynamic_attachment`")  # noqa: E501
        # verify the required parameter 'attachment_key' is set
        if ('attachment_key' not in local_var_params or
                local_var_params['attachment_key'] is None):
            raise ValueError("Missing the required parameter `attachment_key` when calling `type_get_dynamic_attachment`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'type_id' in local_var_params:
            path_params['type_id'] = local_var_params['type_id']  # noqa: E501
        if 'attachment_key' in local_var_params:
            path_params['attachment_key'] = local_var_params['attachment_key']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Authorization']  # noqa: E501

        return self.api_client.call_api(
            '/type/{type_id}/dynamic_attachment/{attachment_key}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Response',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def type_parent(self, type_id, **kwargs):  # noqa: E501
        """Get the parent type identifier of the data structure referenced by the identifier.  # noqa: E501

        Get the parent type identifier of the data structure referenced by the identifier.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.type_parent(type_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str type_id: (required)
        :return: Response
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.type_parent_with_http_info(type_id, **kwargs)  # noqa: E501
        else:
            (data) = self.type_parent_with_http_info(type_id, **kwargs)  # noqa: E501
            return data

    def type_parent_with_http_info(self, type_id, **kwargs):  # noqa: E501
        """Get the parent type identifier of the data structure referenced by the identifier.  # noqa: E501

        Get the parent type identifier of the data structure referenced by the identifier.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.type_parent_with_http_info(type_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str type_id: (required)
        :return: Response
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['type_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method type_parent" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'type_id' is set
        if ('type_id' not in local_var_params or
                local_var_params['type_id'] is None):
            raise ValueError("Missing the required parameter `type_id` when calling `type_parent`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'type_id' in local_var_params:
            path_params['type_id'] = local_var_params['type_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Authorization']  # noqa: E501

        return self.api_client.call_api(
            '/type/{type_id}/parent', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Response',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def type_query(self, body, **kwargs):  # noqa: E501
        """Query with JMESPath.  # noqa: E501

        Query with JMESPath.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.type_query(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str body: (required)
        :return: Response
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.type_query_with_http_info(body, **kwargs)  # noqa: E501
        else:
            (data) = self.type_query_with_http_info(body, **kwargs)  # noqa: E501
            return data

    def type_query_with_http_info(self, body, **kwargs):  # noqa: E501
        """Query with JMESPath.  # noqa: E501

        Query with JMESPath.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.type_query_with_http_info(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str body: (required)
        :return: Response
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method type_query" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in local_var_params or
                local_var_params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `type_query`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in local_var_params:
            body_params = local_var_params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Authorization']  # noqa: E501

        return self.api_client.call_api(
            '/query', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Response',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def type_reflect(self, type_id, **kwargs):  # noqa: E501
        """Get the runtime type of the data structure referenced by the identifier.  # noqa: E501

        Get the runtime type of the data structure referenced by the identifier.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.type_reflect(type_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str type_id: (required)
        :return: Response
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.type_reflect_with_http_info(type_id, **kwargs)  # noqa: E501
        else:
            (data) = self.type_reflect_with_http_info(type_id, **kwargs)  # noqa: E501
            return data

    def type_reflect_with_http_info(self, type_id, **kwargs):  # noqa: E501
        """Get the runtime type of the data structure referenced by the identifier.  # noqa: E501

        Get the runtime type of the data structure referenced by the identifier.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.type_reflect_with_http_info(type_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str type_id: (required)
        :return: Response
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['type_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method type_reflect" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'type_id' is set
        if ('type_id' not in local_var_params or
                local_var_params['type_id'] is None):
            raise ValueError("Missing the required parameter `type_id` when calling `type_reflect`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'type_id' in local_var_params:
            path_params['type_id'] = local_var_params['type_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Authorization']  # noqa: E501

        return self.api_client.call_api(
            '/type/{type_id}/reflect', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Response',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def type_set_attachment(self, type_id, attachment_key, **kwargs):  # noqa: E501
        """type_set_attachment  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.type_set_attachment(type_id, attachment_key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str type_id: (required)
        :param str attachment_key: (required)
        :param InlineObject inline_object:
        :return: Response
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.type_set_attachment_with_http_info(type_id, attachment_key, **kwargs)  # noqa: E501
        else:
            (data) = self.type_set_attachment_with_http_info(type_id, attachment_key, **kwargs)  # noqa: E501
            return data

    def type_set_attachment_with_http_info(self, type_id, attachment_key, **kwargs):  # noqa: E501
        """type_set_attachment  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.type_set_attachment_with_http_info(type_id, attachment_key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str type_id: (required)
        :param str attachment_key: (required)
        :param InlineObject inline_object:
        :return: Response
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['type_id', 'attachment_key', 'inline_object']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method type_set_attachment" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'type_id' is set
        if ('type_id' not in local_var_params or
                local_var_params['type_id'] is None):
            raise ValueError("Missing the required parameter `type_id` when calling `type_set_attachment`")  # noqa: E501
        # verify the required parameter 'attachment_key' is set
        if ('attachment_key' not in local_var_params or
                local_var_params['attachment_key'] is None):
            raise ValueError("Missing the required parameter `attachment_key` when calling `type_set_attachment`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'type_id' in local_var_params:
            path_params['type_id'] = local_var_params['type_id']  # noqa: E501
        if 'attachment_key' in local_var_params:
            path_params['attachment_key'] = local_var_params['attachment_key']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'inline_object' in local_var_params:
            body_params = local_var_params['inline_object']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Authorization']  # noqa: E501

        return self.api_client.call_api(
            '/type/{type_id}/attachment/{attachment_key}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Response',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def type_set_dynamic_attachment(self, type_id, attachment_key, **kwargs):  # noqa: E501
        """type_set_dynamic_attachment  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.type_set_dynamic_attachment(type_id, attachment_key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str type_id: (required)
        :param str attachment_key: (required)
        :param InlineObject1 inline_object1:
        :return: Response
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.type_set_dynamic_attachment_with_http_info(type_id, attachment_key, **kwargs)  # noqa: E501
        else:
            (data) = self.type_set_dynamic_attachment_with_http_info(type_id, attachment_key, **kwargs)  # noqa: E501
            return data

    def type_set_dynamic_attachment_with_http_info(self, type_id, attachment_key, **kwargs):  # noqa: E501
        """type_set_dynamic_attachment  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.type_set_dynamic_attachment_with_http_info(type_id, attachment_key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str type_id: (required)
        :param str attachment_key: (required)
        :param InlineObject1 inline_object1:
        :return: Response
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['type_id', 'attachment_key', 'inline_object1']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method type_set_dynamic_attachment" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'type_id' is set
        if ('type_id' not in local_var_params or
                local_var_params['type_id'] is None):
            raise ValueError("Missing the required parameter `type_id` when calling `type_set_dynamic_attachment`")  # noqa: E501
        # verify the required parameter 'attachment_key' is set
        if ('attachment_key' not in local_var_params or
                local_var_params['attachment_key'] is None):
            raise ValueError("Missing the required parameter `attachment_key` when calling `type_set_dynamic_attachment`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'type_id' in local_var_params:
            path_params['type_id'] = local_var_params['type_id']  # noqa: E501
        if 'attachment_key' in local_var_params:
            path_params['attachment_key'] = local_var_params['attachment_key']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'inline_object1' in local_var_params:
            body_params = local_var_params['inline_object1']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Authorization']  # noqa: E501

        return self.api_client.call_api(
            '/type/{type_id}/dynamic_attachment/{attachment_key}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Response',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)
