SurveyQuestionDict = {'Today I feel little interest or pleasure':'Mood',
				 	  'Today I feel depressed':'Mood',
				 	  'Today I had trouble sleeping':'Mood',
					  'Today I feel tired or have little energy':'Mood',
					  'Today I have a poor appetite or am overeating':'Mood',
					  'Today I feel bad about myself or that I have let others down':'Mood',
					  'Today I have trouble focusing or concentrating':'Mood',
					  'Today I feel too slow or too restless':'Mood',
					  'Today I have thoughts of self-harm':'Mood',
					  'Last night I had trouble staying asleep':'Sleep',
					  'Last night I have had trouble falling asleep':'Sleep',
					  'This morning I was up earlier than I wanted':'Sleep',
					  'In the last THREE DAYS, I have taken my medications as scheduled':'Medication',
					  'In the last THREE DAYS, during the daytime I have gone outside my home':'Social_Reverse',
					  'In the last THREE DAYS, I have had someone to talk to':'Social_Reverse',
			 		  'In the last THREE DAYS, I have preferred to spend time alone':'Social',
					  'In the last THREE DAYS, I have felt uneasy with groups of people':'Social',
					  'In the last THREE DAYS, I have had arguments with other people':'Social',
					  'Today I feel anxious':'Anxiety',
					  'Today I cannot stop worrying':'Anxiety',
					  'Today I am worrying too much about different things':'Anxiety',
					  'Today I have trouble relaxing':'Anxiety',
					  'Today I feel so restless it\'s hard to sit still':'Anxiety',
					  'Today I am easily annoyed or irritable':'Anxiety',
					  'Today I feel afraid something awful might happen':'Anxiety',
					  'Today I have heard voices or saw things others cannot':'Psychosis',
					  'Today I have had thoughts racing through my head':'Psychosis',
					  'Today I feel I have special powers':'Psychosis',
					  'Today I feel people are watching me':'Psychosis',
					  'Today I feel people are against me':'Psychosis',
					  'Today I feel confused or puzzled':'Psychosis',
					  'Today I feel unable to cope and have difficulty with everyday tasks':'Psychosis',
                      'In the last THREE DAYS, I have had trouble falling asleep':'Sleep',
                      'In the last THREE DAYS, I had trouble staying asleep':'Sleep',
                      'In the last THREE DAYS, I was up earlier than I wanted':'Sleep',
                      'Do you feel like you\'ve had nutritious meals today?':'Water and Nutrition',
                      'How much water have you drank today?':'Water and Nutrition',
                      'I trust this app to guide me towards my personal goals':'App Usability',
                      'I believe this app\'s tasks will help me to address my problem':'App Usability',
                      'This app encourages me to accomplish tasks and make progress':'App Usability',
                      'I agree that the tasks within this app are important for my goals':'App Usability',
                      'This app is easy to use and operate':'App Usability',
                      'This app supports me to overcome challenges':'App Usability'}