# coding: utf-8

"""
    LAMP Platform

    The LAMP Platform API.  # noqa: E501

    OpenAPI spec version: 0.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class InlineObject2(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'script_type': 'str',
        'script_contents': 'str',
        'script_requirements': 'list[str]'
    }

    attribute_map = {
        'script_type': 'script_type',
        'script_contents': 'script_contents',
        'script_requirements': 'script_requirements'
    }

    def __init__(self, script_type=None, script_contents=None, script_requirements=None):  # noqa: E501
        """InlineObject2 - a model defined in OpenAPI"""  # noqa: E501

        self._script_type = None
        self._script_contents = None
        self._script_requirements = None
        self.discriminator = None

        self.script_type = script_type
        self.script_contents = script_contents
        self.script_requirements = script_requirements

    @property
    def script_type(self):
        """Gets the script_type of this InlineObject2.  # noqa: E501


        :return: The script_type of this InlineObject2.  # noqa: E501
        :rtype: str
        """
        return self._script_type

    @script_type.setter
    def script_type(self, script_type):
        """Sets the script_type of this InlineObject2.


        :param script_type: The script_type of this InlineObject2.  # noqa: E501
        :type: str
        """
        if script_type is None:
            raise ValueError("Invalid value for `script_type`, must not be `None`")  # noqa: E501

        self._script_type = script_type

    @property
    def script_contents(self):
        """Gets the script_contents of this InlineObject2.  # noqa: E501


        :return: The script_contents of this InlineObject2.  # noqa: E501
        :rtype: str
        """
        return self._script_contents

    @script_contents.setter
    def script_contents(self, script_contents):
        """Sets the script_contents of this InlineObject2.


        :param script_contents: The script_contents of this InlineObject2.  # noqa: E501
        :type: str
        """
        if script_contents is None:
            raise ValueError("Invalid value for `script_contents`, must not be `None`")  # noqa: E501

        self._script_contents = script_contents

    @property
    def script_requirements(self):
        """Gets the script_requirements of this InlineObject2.  # noqa: E501


        :return: The script_requirements of this InlineObject2.  # noqa: E501
        :rtype: list[str]
        """
        return self._script_requirements

    @script_requirements.setter
    def script_requirements(self, script_requirements):
        """Sets the script_requirements of this InlineObject2.


        :param script_requirements: The script_requirements of this InlineObject2.  # noqa: E501
        :type: list[str]
        """
        if script_requirements is None:
            raise ValueError("Invalid value for `script_requirements`, must not be `None`")  # noqa: E501

        self._script_requirements = script_requirements

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineObject2):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
