# coding: utf-8

"""
    LAMP Platform

    The LAMP Platform API.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class Researcher(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'name': 'str',
        'email': 'str',
        'address': 'str',
        'studies': 'list[object]'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'email': 'email',
        'address': 'address',
        'studies': 'studies'
    }

    def __init__(self, id=None, name=None, email=None, address=None, studies=None, local_vars_configuration=None):  # noqa: E501
        """Researcher - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._name = None
        self._email = None
        self._address = None
        self._studies = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if email is not None:
            self.email = email
        if address is not None:
            self.address = address
        if studies is not None:
            self.studies = studies

    @property
    def id(self):
        """Gets the id of this Researcher.  # noqa: E501

        A globally unique reference for objects.  # noqa: E501

        :return: The id of this Researcher.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Researcher.

        A globally unique reference for objects.  # noqa: E501

        :param id: The id of this Researcher.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this Researcher.  # noqa: E501

        The name of the researcher.  # noqa: E501

        :return: The name of this Researcher.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Researcher.

        The name of the researcher.  # noqa: E501

        :param name: The name of this Researcher.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def email(self):
        """Gets the email of this Researcher.  # noqa: E501

        The email address of the researcher.  # noqa: E501

        :return: The email of this Researcher.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this Researcher.

        The email address of the researcher.  # noqa: E501

        :param email: The email of this Researcher.  # noqa: E501
        :type: str
        """

        self._email = email

    @property
    def address(self):
        """Gets the address of this Researcher.  # noqa: E501

        The physical address of the researcher.  # noqa: E501

        :return: The address of this Researcher.  # noqa: E501
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this Researcher.

        The physical address of the researcher.  # noqa: E501

        :param address: The address of this Researcher.  # noqa: E501
        :type: str
        """

        self._address = address

    @property
    def studies(self):
        """Gets the studies of this Researcher.  # noqa: E501

        The set of all studies conducted by the researcher.  # noqa: E501

        :return: The studies of this Researcher.  # noqa: E501
        :rtype: list[object]
        """
        return self._studies

    @studies.setter
    def studies(self, studies):
        """Sets the studies of this Researcher.

        The set of all studies conducted by the researcher.  # noqa: E501

        :param studies: The studies of this Researcher.  # noqa: E501
        :type: list[object]
        """

        self._studies = studies

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Researcher):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Researcher):
            return True

        return self.to_dict() != other.to_dict()
