# coding: utf-8

"""
    LAMP Platform

    The LAMP Platform API.  # noqa: E501

    OpenAPI spec version: 0.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class MetadataEvent(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'attachments': 'dict(str, object)',
        'type': 'MetadataEventType',
        'timestamp': 'int',
        'item': 'str'
    }

    attribute_map = {
        'id': 'id',
        'attachments': 'attachments',
        'type': 'type',
        'timestamp': 'timestamp',
        'item': 'item'
    }

    def __init__(self, id=None, attachments=None, type=None, timestamp=None, item=None):  # noqa: E501
        """MetadataEvent - a model defined in OpenAPI"""  # noqa: E501

        self._id = None
        self._attachments = None
        self._type = None
        self._timestamp = None
        self._item = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if attachments is not None:
            self.attachments = attachments
        if type is not None:
            self.type = type
        if timestamp is not None:
            self.timestamp = timestamp
        if item is not None:
            self.item = item

    @property
    def id(self):
        """Gets the id of this MetadataEvent.  # noqa: E501

        A globally unique reference for objects within the LAMP platform.  # noqa: E501

        :return: The id of this MetadataEvent.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this MetadataEvent.

        A globally unique reference for objects within the LAMP platform.  # noqa: E501

        :param id: The id of this MetadataEvent.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def attachments(self):
        """Gets the attachments of this MetadataEvent.  # noqa: E501


        :return: The attachments of this MetadataEvent.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._attachments

    @attachments.setter
    def attachments(self, attachments):
        """Sets the attachments of this MetadataEvent.


        :param attachments: The attachments of this MetadataEvent.  # noqa: E501
        :type: dict(str, object)
        """

        self._attachments = attachments

    @property
    def type(self):
        """Gets the type of this MetadataEvent.  # noqa: E501


        :return: The type of this MetadataEvent.  # noqa: E501
        :rtype: MetadataEventType
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this MetadataEvent.


        :param type: The type of this MetadataEvent.  # noqa: E501
        :type: MetadataEventType
        """

        self._type = type

    @property
    def timestamp(self):
        """Gets the timestamp of this MetadataEvent.  # noqa: E501


        :return: The timestamp of this MetadataEvent.  # noqa: E501
        :rtype: int
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this MetadataEvent.


        :param timestamp: The timestamp of this MetadataEvent.  # noqa: E501
        :type: int
        """

        self._timestamp = timestamp

    @property
    def item(self):
        """Gets the item of this MetadataEvent.  # noqa: E501

        The item information recorded within the metadata event.  # noqa: E501

        :return: The item of this MetadataEvent.  # noqa: E501
        :rtype: str
        """
        return self._item

    @item.setter
    def item(self, item):
        """Sets the item of this MetadataEvent.

        The item information recorded within the metadata event.  # noqa: E501

        :param item: The item of this MetadataEvent.  # noqa: E501
        :type: str
        """

        self._item = item

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MetadataEvent):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
