# coding: utf-8

"""
    LAMP Platform

    The LAMP Platform API.  # noqa: E501

    OpenAPI spec version: 0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from openapi_client.api_client import ApiClient


class ResearcherApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def researcher_all(self, **kwargs):  # noqa: E501
        """Get the set of all researchers.  # noqa: E501

        Get the set of all researchers.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.researcher_all(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: Response
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.researcher_all_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.researcher_all_with_http_info(**kwargs)  # noqa: E501
            return data

    def researcher_all_with_http_info(self, **kwargs):  # noqa: E501
        """Get the set of all researchers.  # noqa: E501

        Get the set of all researchers.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.researcher_all_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: Response
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method researcher_all" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Authorization']  # noqa: E501

        return self.api_client.call_api(
            '/researcher/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Response',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def researcher_create(self, sensor_event, **kwargs):  # noqa: E501
        """Get a single researcher, by an identifier.  # noqa: E501

        Get a single researcher, by an identifier.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.researcher_create(sensor_event, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param SensorEvent sensor_event: (required)
        :return: Response
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.researcher_create_with_http_info(sensor_event, **kwargs)  # noqa: E501
        else:
            (data) = self.researcher_create_with_http_info(sensor_event, **kwargs)  # noqa: E501
            return data

    def researcher_create_with_http_info(self, sensor_event, **kwargs):  # noqa: E501
        """Get a single researcher, by an identifier.  # noqa: E501

        Get a single researcher, by an identifier.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.researcher_create_with_http_info(sensor_event, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param SensorEvent sensor_event: (required)
        :return: Response
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['sensor_event']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method researcher_create" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'sensor_event' is set
        if ('sensor_event' not in local_var_params or
                local_var_params['sensor_event'] is None):
            raise ValueError("Missing the required parameter `sensor_event` when calling `researcher_create`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'sensor_event' in local_var_params:
            body_params = local_var_params['sensor_event']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Authorization']  # noqa: E501

        return self.api_client.call_api(
            '/researcher', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Response',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def researcher_delete(self, researcher_id, **kwargs):  # noqa: E501
        """Get a single researcher, by an identifier.  # noqa: E501

        Get a single researcher, by an identifier.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.researcher_delete(researcher_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str researcher_id: (required)
        :return: Response
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.researcher_delete_with_http_info(researcher_id, **kwargs)  # noqa: E501
        else:
            (data) = self.researcher_delete_with_http_info(researcher_id, **kwargs)  # noqa: E501
            return data

    def researcher_delete_with_http_info(self, researcher_id, **kwargs):  # noqa: E501
        """Get a single researcher, by an identifier.  # noqa: E501

        Get a single researcher, by an identifier.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.researcher_delete_with_http_info(researcher_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str researcher_id: (required)
        :return: Response
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['researcher_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method researcher_delete" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'researcher_id' is set
        if ('researcher_id' not in local_var_params or
                local_var_params['researcher_id'] is None):
            raise ValueError("Missing the required parameter `researcher_id` when calling `researcher_delete`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'researcher_id' in local_var_params:
            path_params['researcher_id'] = local_var_params['researcher_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Authorization']  # noqa: E501

        return self.api_client.call_api(
            '/researcher/{researcher_id}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Response',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def researcher_update(self, researcher_id, researcher, **kwargs):  # noqa: E501
        """Get a single researcher, by an identifier.  # noqa: E501

        Get a single researcher, by an identifier.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.researcher_update(researcher_id, researcher, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str researcher_id: (required)
        :param Researcher researcher: (required)
        :return: Response
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.researcher_update_with_http_info(researcher_id, researcher, **kwargs)  # noqa: E501
        else:
            (data) = self.researcher_update_with_http_info(researcher_id, researcher, **kwargs)  # noqa: E501
            return data

    def researcher_update_with_http_info(self, researcher_id, researcher, **kwargs):  # noqa: E501
        """Get a single researcher, by an identifier.  # noqa: E501

        Get a single researcher, by an identifier.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.researcher_update_with_http_info(researcher_id, researcher, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str researcher_id: (required)
        :param Researcher researcher: (required)
        :return: Response
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['researcher_id', 'researcher']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method researcher_update" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'researcher_id' is set
        if ('researcher_id' not in local_var_params or
                local_var_params['researcher_id'] is None):
            raise ValueError("Missing the required parameter `researcher_id` when calling `researcher_update`")  # noqa: E501
        # verify the required parameter 'researcher' is set
        if ('researcher' not in local_var_params or
                local_var_params['researcher'] is None):
            raise ValueError("Missing the required parameter `researcher` when calling `researcher_update`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'researcher_id' in local_var_params:
            path_params['researcher_id'] = local_var_params['researcher_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'researcher' in local_var_params:
            body_params = local_var_params['researcher']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Authorization']  # noqa: E501

        return self.api_client.call_api(
            '/researcher/{researcher_id}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Response',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def researcher_view(self, researcher_id, **kwargs):  # noqa: E501
        """Get a single researcher, by an identifier.  # noqa: E501

        Get a single researcher, by an identifier.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.researcher_view(researcher_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str researcher_id: (required)
        :return: Response
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.researcher_view_with_http_info(researcher_id, **kwargs)  # noqa: E501
        else:
            (data) = self.researcher_view_with_http_info(researcher_id, **kwargs)  # noqa: E501
            return data

    def researcher_view_with_http_info(self, researcher_id, **kwargs):  # noqa: E501
        """Get a single researcher, by an identifier.  # noqa: E501

        Get a single researcher, by an identifier.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.researcher_view_with_http_info(researcher_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str researcher_id: (required)
        :return: Response
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['researcher_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method researcher_view" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'researcher_id' is set
        if ('researcher_id' not in local_var_params or
                local_var_params['researcher_id'] is None):
            raise ValueError("Missing the required parameter `researcher_id` when calling `researcher_view`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'researcher_id' in local_var_params:
            path_params['researcher_id'] = local_var_params['researcher_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Authorization']  # noqa: E501

        return self.api_client.call_api(
            '/researcher/{researcher_id}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Response',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)
