# coding: utf-8

"""
    LAMP Platform

    The LAMP Platform API.  # noqa: E501

    OpenAPI spec version: 0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from openapi_client.api_client import ApiClient


class TypeLegacyApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def type_legacy_export(self, participant_id, **kwargs):  # noqa: E501
        """type_legacy_export  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.type_legacy_export(participant_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str participant_id: (required)
        :return: Response
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.type_legacy_export_with_http_info(participant_id, **kwargs)  # noqa: E501
        else:
            (data) = self.type_legacy_export_with_http_info(participant_id, **kwargs)  # noqa: E501
            return data

    def type_legacy_export_with_http_info(self, participant_id, **kwargs):  # noqa: E501
        """type_legacy_export  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.type_legacy_export_with_http_info(participant_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str participant_id: (required)
        :return: Response
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['participant_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method type_legacy_export" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'participant_id' is set
        if ('participant_id' not in local_var_params or
                local_var_params['participant_id'] is None):
            raise ValueError("Missing the required parameter `participant_id` when calling `type_legacy_export`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'participant_id' in local_var_params:
            path_params['participant_id'] = local_var_params['participant_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Authorization']  # noqa: E501

        return self.api_client.call_api(
            '/participant/{participant_id}/export', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Response',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def type_legacy_get_attachment(self, participant_id, attachment_key, **kwargs):  # noqa: E501
        """type_legacy_get_attachment  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.type_legacy_get_attachment(participant_id, attachment_key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str participant_id: (required)
        :param str attachment_key: (required)
        :return: Response
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.type_legacy_get_attachment_with_http_info(participant_id, attachment_key, **kwargs)  # noqa: E501
        else:
            (data) = self.type_legacy_get_attachment_with_http_info(participant_id, attachment_key, **kwargs)  # noqa: E501
            return data

    def type_legacy_get_attachment_with_http_info(self, participant_id, attachment_key, **kwargs):  # noqa: E501
        """type_legacy_get_attachment  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.type_legacy_get_attachment_with_http_info(participant_id, attachment_key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str participant_id: (required)
        :param str attachment_key: (required)
        :return: Response
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['participant_id', 'attachment_key']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method type_legacy_get_attachment" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'participant_id' is set
        if ('participant_id' not in local_var_params or
                local_var_params['participant_id'] is None):
            raise ValueError("Missing the required parameter `participant_id` when calling `type_legacy_get_attachment`")  # noqa: E501
        # verify the required parameter 'attachment_key' is set
        if ('attachment_key' not in local_var_params or
                local_var_params['attachment_key'] is None):
            raise ValueError("Missing the required parameter `attachment_key` when calling `type_legacy_get_attachment`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'participant_id' in local_var_params:
            path_params['participant_id'] = local_var_params['participant_id']  # noqa: E501
        if 'attachment_key' in local_var_params:
            path_params['attachment_key'] = local_var_params['attachment_key']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Authorization']  # noqa: E501

        return self.api_client.call_api(
            '/participant/{participant_id}/attachment/{attachment_key}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Response',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def type_legacy_set_attachment(self, researcher_id, attachment_key, **kwargs):  # noqa: E501
        """type_legacy_set_attachment  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.type_legacy_set_attachment(researcher_id, attachment_key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str researcher_id: (required)
        :param str attachment_key: (required)
        :param InlineObject2 inline_object2:
        :return: Response
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.type_legacy_set_attachment_with_http_info(researcher_id, attachment_key, **kwargs)  # noqa: E501
        else:
            (data) = self.type_legacy_set_attachment_with_http_info(researcher_id, attachment_key, **kwargs)  # noqa: E501
            return data

    def type_legacy_set_attachment_with_http_info(self, researcher_id, attachment_key, **kwargs):  # noqa: E501
        """type_legacy_set_attachment  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.type_legacy_set_attachment_with_http_info(researcher_id, attachment_key, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str researcher_id: (required)
        :param str attachment_key: (required)
        :param InlineObject2 inline_object2:
        :return: Response
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['researcher_id', 'attachment_key', 'inline_object2']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method type_legacy_set_attachment" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'researcher_id' is set
        if ('researcher_id' not in local_var_params or
                local_var_params['researcher_id'] is None):
            raise ValueError("Missing the required parameter `researcher_id` when calling `type_legacy_set_attachment`")  # noqa: E501
        # verify the required parameter 'attachment_key' is set
        if ('attachment_key' not in local_var_params or
                local_var_params['attachment_key'] is None):
            raise ValueError("Missing the required parameter `attachment_key` when calling `type_legacy_set_attachment`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'researcher_id' in local_var_params:
            path_params['researcher_id'] = local_var_params['researcher_id']  # noqa: E501
        if 'attachment_key' in local_var_params:
            path_params['attachment_key'] = local_var_params['attachment_key']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'inline_object2' in local_var_params:
            body_params = local_var_params['inline_object2']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Authorization']  # noqa: E501

        return self.api_client.call_api(
            '/researcher/{researcher_id}/attachment/{attachment_key}', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Response',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)
