# coding: utf-8

"""
    LAMP Platform

    The LAMP Platform API.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from lamp.configuration import Configuration


class Activity(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'spec': 'str',
        'name': 'str',
        'schedule': 'DurationIntervalLegacy',
        'settings': 'object'
    }

    attribute_map = {
        'id': 'id',
        'spec': 'spec',
        'name': 'name',
        'schedule': 'schedule',
        'settings': 'settings'
    }

    def __init__(self, id=None, spec=None, name=None, schedule=None, settings=None, local_vars_configuration=None):  # noqa: E501
        """Activity - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._spec = None
        self._name = None
        self._schedule = None
        self._settings = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if spec is not None:
            self.spec = spec
        if name is not None:
            self.name = name
        if schedule is not None:
            self.schedule = schedule
        if settings is not None:
            self.settings = settings

    @property
    def id(self):
        """Gets the id of this Activity.  # noqa: E501

        A globally unique reference for objects.  # noqa: E501

        :return: The id of this Activity.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Activity.

        A globally unique reference for objects.  # noqa: E501

        :param id: The id of this Activity.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def spec(self):
        """Gets the spec of this Activity.  # noqa: E501

        A globally unique reference for objects.  # noqa: E501

        :return: The spec of this Activity.  # noqa: E501
        :rtype: str
        """
        return self._spec

    @spec.setter
    def spec(self, spec):
        """Sets the spec of this Activity.

        A globally unique reference for objects.  # noqa: E501

        :param spec: The spec of this Activity.  # noqa: E501
        :type: str
        """

        self._spec = spec

    @property
    def name(self):
        """Gets the name of this Activity.  # noqa: E501

        The name of the activity.  # noqa: E501

        :return: The name of this Activity.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Activity.

        The name of the activity.  # noqa: E501

        :param name: The name of this Activity.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def schedule(self):
        """Gets the schedule of this Activity.  # noqa: E501


        :return: The schedule of this Activity.  # noqa: E501
        :rtype: DurationIntervalLegacy
        """
        return self._schedule

    @schedule.setter
    def schedule(self, schedule):
        """Sets the schedule of this Activity.


        :param schedule: The schedule of this Activity.  # noqa: E501
        :type: DurationIntervalLegacy
        """

        self._schedule = schedule

    @property
    def settings(self):
        """Gets the settings of this Activity.  # noqa: E501

        The configuration settings for the activity.  # noqa: E501

        :return: The settings of this Activity.  # noqa: E501
        :rtype: object
        """
        return self._settings

    @settings.setter
    def settings(self, settings):
        """Sets the settings of this Activity.

        The configuration settings for the activity.  # noqa: E501

        :param settings: The settings of this Activity.  # noqa: E501
        :type: object
        """

        self._settings = settings

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Activity):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Activity):
            return True

        return self.to_dict() != other.to_dict()
