# coding: utf-8

"""
    LAMP Platform

    The LAMP Platform API.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from lamp.configuration import Configuration


class DurationInterval(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'start': 'float',
        'interval': 'list[object]',
        'repeat_count': 'int',
        'end': 'float'
    }

    attribute_map = {
        'start': 'start',
        'interval': 'interval',
        'repeat_count': 'repeat_count',
        'end': 'end'
    }

    def __init__(self, start=None, interval=None, repeat_count=None, end=None, local_vars_configuration=None):  # noqa: E501
        """DurationInterval - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._start = None
        self._interval = None
        self._repeat_count = None
        self._end = None
        self.discriminator = None

        if start is not None:
            self.start = start
        if interval is not None:
            self.interval = interval
        if repeat_count is not None:
            self.repeat_count = repeat_count
        if end is not None:
            self.end = end

    @property
    def start(self):
        """Gets the start of this DurationInterval.  # noqa: E501

        The UNIX Epoch date-time representation: number of milliseconds since 1/1/1970 12:00 AM.  # noqa: E501

        :return: The start of this DurationInterval.  # noqa: E501
        :rtype: float
        """
        return self._start

    @start.setter
    def start(self, start):
        """Sets the start of this DurationInterval.

        The UNIX Epoch date-time representation: number of milliseconds since 1/1/1970 12:00 AM.  # noqa: E501

        :param start: The start of this DurationInterval.  # noqa: E501
        :type: float
        """

        self._start = start

    @property
    def interval(self):
        """Gets the interval of this DurationInterval.  # noqa: E501


        :return: The interval of this DurationInterval.  # noqa: E501
        :rtype: list[object]
        """
        return self._interval

    @interval.setter
    def interval(self, interval):
        """Sets the interval of this DurationInterval.


        :param interval: The interval of this DurationInterval.  # noqa: E501
        :type: list[object]
        """

        self._interval = interval

    @property
    def repeat_count(self):
        """Gets the repeat_count of this DurationInterval.  # noqa: E501


        :return: The repeat_count of this DurationInterval.  # noqa: E501
        :rtype: int
        """
        return self._repeat_count

    @repeat_count.setter
    def repeat_count(self, repeat_count):
        """Sets the repeat_count of this DurationInterval.


        :param repeat_count: The repeat_count of this DurationInterval.  # noqa: E501
        :type: int
        """

        self._repeat_count = repeat_count

    @property
    def end(self):
        """Gets the end of this DurationInterval.  # noqa: E501

        The UNIX Epoch date-time representation: number of milliseconds since 1/1/1970 12:00 AM.  # noqa: E501

        :return: The end of this DurationInterval.  # noqa: E501
        :rtype: float
        """
        return self._end

    @end.setter
    def end(self, end):
        """Sets the end of this DurationInterval.

        The UNIX Epoch date-time representation: number of milliseconds since 1/1/1970 12:00 AM.  # noqa: E501

        :param end: The end of this DurationInterval.  # noqa: E501
        :type: float
        """

        self._end = end

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DurationInterval):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, DurationInterval):
            return True

        return self.to_dict() != other.to_dict()
