# coding: utf-8

"""
    LAMP Platform

    The LAMP Platform API.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from lamp.configuration import Configuration


class SensorSpec(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'name': 'str',
        'settings_schema': 'object'
    }

    attribute_map = {
        'name': 'name',
        'settings_schema': 'settings_schema'
    }

    def __init__(self, name=None, settings_schema=None, local_vars_configuration=None):  # noqa: E501
        """SensorSpec - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._name = None
        self._settings_schema = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if settings_schema is not None:
            self.settings_schema = settings_schema

    @property
    def name(self):
        """Gets the name of this SensorSpec.  # noqa: E501

        The name of the sensor.  # noqa: E501

        :return: The name of this SensorSpec.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SensorSpec.

        The name of the sensor.  # noqa: E501

        :param name: The name of this SensorSpec.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def settings_schema(self):
        """Gets the settings_schema of this SensorSpec.  # noqa: E501

        The data definition of a SensorSpec.  # noqa: E501

        :return: The settings_schema of this SensorSpec.  # noqa: E501
        :rtype: object
        """
        return self._settings_schema

    @settings_schema.setter
    def settings_schema(self, settings_schema):
        """Sets the settings_schema of this SensorSpec.

        The data definition of a SensorSpec.  # noqa: E501

        :param settings_schema: The settings_schema of this SensorSpec.  # noqa: E501
        :type: object
        """

        self._settings_schema = settings_schema

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SensorSpec):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SensorSpec):
            return True

        return self.to_dict() != other.to_dict()
